### ISSUE TITLE
[REFACTOR] 서버 최적화 구현

### ISSUE THREAD

**Issue by rlarlgnszx** [wakawaka-CONTACTO/contacto-server#68]
## 🛠 Issue

서버 최적화 
## 📝 To-do

- [ ] 서버 최적화 
- [ ] 쿼리 최적화
- [ ] DB 조회 최적화
- [ ] Cache 추가 구현 
- [ ] Logging 추가 구현
